### ISSUE TITLE
ENH: Add ability to feed description into issues

### ISSUE THREAD

**Issue by MathewBiddle** [hackthackathon/hackathon-template-cookiecutter#10]
https://github.com/hackthackathon/hackathon-template-cookiecutter/blob/main/%7B%7Bcookiecutter.hackathon_repo_name%7D%7D/checklist-issues.txt

Update 
https://github.com/hackthackathon/hackathon-template-cookiecutter/blob/main/%7B%7Bcookiecutter.hackathon_repo_name%7D%7D/scripts/create_issues.py

https://pygithub.readthedocs.io/en/stable/github_objects/Repository.html?highlight=create_issue#github.Repository.Repository.create_issue

add `body=`

**Comment by mgrover1** [comment]
Closed by #17
