### ISSUE TITLE
BUG: How to keep Actions up-to-date for {{ cookiecutter }}

### ISSUE THREAD

**Issue by MathewBiddle** [hackthackathon/hackathon-template-cookiecutter#12]
dependabot lives in `.github/` and checks workflows in `.github/workflows/`. 

How do we keep the actions up-to-date in https://github.com/hackthackathon/hackathon-template-cookiecutter/tree/main/%7B%7Bcookiecutter.hackathon_repo_name%7D%7D/.github/workflows ?

**Comment by mgrover1** [comment]
This is closed with #18
